import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../styles/globals.css";
import { Toaster } from "@/components/alert/toaster";
import Providers from '@/components/user/providers'; 

export const metadata: Metadata = {
  title: "Clarify",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head />
      <body>
        <Providers> 
          <main>{children}</main>
          <Toaster />
        </Providers>
      </body>
    </html>
  );
}
